env:
  node: true
  browser: true
  commonjs: true
  es6: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: {
  no-console: 0,
  no-unused-vars: ["error", { "vars": "all", "args": "none"}],
  linebreak-style: ["error", "unix"],
  quotes: ["error", "single"],
  semi: ["error", "always"],
  no-trailing-spaces: ["error"]
}
